# Generated by Django 5.1.6 on 2025-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
