# Generated by Django 5.1.6 on 2025-02-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_location_profile_prompt_answers_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dream_vacation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_truths_and_a_lie',
            field=models.TextField(blank=True),
        ),
    ]
